### ISSUE TITLE
Blank page when trying to edit pages

### ISSUE THREAD

**Issue by tmo26** [hokkaidoperson/DokuWiki-StopForumSpam2-Plugin#1]
Dokuwiki version: 2018-04-22b "Greebo"
Stopforumspam2 version: 2019-02-06

Issue: After installation of stopforumspam2 editing of pages is not possible any more, since all that is shown after clicking on "Edit" is a blank wiki page (no sidebar, no text, noedit area, just the wiki background).

This occures although I have set the following:
skipMgAndSp = Skip managers (including superusers) -> I'm a wiki admin, so that should include me
emailWhitelist -> added myself

Setting the following to zero let's me edit pages again:
freqBorder = 0
confidenceBorder = 0
protectEditFreq = 0
protectEditConf = 0

I checked my  emailadress and username on stopforumspam.com, but as expected didn't find any results at all.

How can I troubleshoot / further analyze this? How can I see what stopforumspam2 is actually doing when I try to edit a page?

**Comment by tmo26** [comment]
@hokkaidoperson I'd be thankfull for any pointers on how to troubleshoot this issue.

**Comment by hokkaidoperson** [comment]
I'm sorry that I got late to notice your comment.
I'll investigate the issue.

**Comment by hokkaidoperson** [comment]
I'm afraid I can't reproduce your issue.

I want to know what's happening on your website, so please do following things:

1. Paste the following code to the top of stopforumspam2/action.php
```
    ini_set("display_errors", 1);
    error_reporting(E_ERROR | E_WARNING | E_PARSE);
```
2. Go to the edit page of your wiki, and you'll find the text beginning with "Fatal Error."
3. Send me the error text to me via email: dosankomali@yahoo.co.jp
4. After sending the error text, remove the code you added when doing "1."

**Comment by tmo26** [comment]
Thanks for your quick reply!

At first I couldn't replicate the issue either, but after purging the page cache (?purge=true) and browser cache (ctrl-F5) it suddenly happened again.

Here is the requested output:

`Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/dokuwiki/lib/plugins/stopforumspam2/helper.php:39 Stack trace: #0 /var/www/dokuwiki/lib/plugins/stopforumspam2/helper.php(74): helper_plugin_stopforumspam2->rawdata('91.7.110.184', NULL, NULL) #1 /var/www/dokuwiki/lib/plugins/stopforumspam2/helper.php(163): helper_plugin_stopforumspam2->freqcheck('91.7.110.184', NULL, NULL, false, '3') #2 /var/www/dokuwiki/lib/plugins/stopforumspam2/action.php(58): helper_plugin_stopforumspam2->quickipcheck('91.7.110.184', '-1', '-1') #3 /var/www/dokuwiki/inc/events.php(229): action_plugin_stopforumspam2->ipprevent(Object(Doku_Event), Array) #4 /var/www/dokuwiki/inc/events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE') #5 /var/www/dokuwiki/inc/events.php(106): Doku_Event->advise_before(true) #6 /var/www/dokuwiki/inc/events.php(256): Doku_Event->trigger('ptln', true) #7 /var/www/dokuwiki/inc/template.php(85): trigger_event('TPL_CONTENT_DIS...', '\n<p>\nEdit the p...', 'ptln') #8 /var/w in /var/www/dokuwiki/lib/plugins/stopforumspam2/helper.php on line 39`

**Comment by hokkaidoperson** [comment]
OK, I figure it out.
It seems that "Client URL Library" (cURL) is not available on your server.
This plugin uses the cURL to get information from the server of StopForumSpam, so please enable the cURL on your server in order to make use of my plugin.
More information: https://www.php.net/manual/en/book.curl.php

**Comment by tmo26** [comment]
`sudo apt-get install php7.0-curl` did the trick!
stopforumspam2 seems to be working now.

Thanks for your help! :)

**Comment by hokkaidoperson** [comment]
That's fine!

**Comment by tmo26** [comment]
Proposal for improvement: Do not just show a blank page when attempting to edit a page, but check for presence of the curl php-extension, and if it is not present, show an error message like "php7.0-curl not found, please install this extension to make this plugin work properly".

**Comment by hokkaidoperson** [comment]
Thanks for your suggestion.
I'll do that.
